### ISSUE TITLE
The Example doesn't work.

### ISSUE THREAD

**Issue by OwenChia** [AgentME/browserify-hmr#31]
Just got this:
```
> example@0.1.0 start ~/work/vue/browserify-hmr/example
> ./scripts/run

Starting up http-server, serving ./
Available on:
  http:127.0.0.1:8080
  http:192.168.0.232:8080
Hit CTRL-C to stop the server
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch ~/work/vue/browserify-hmr/example/node_modules/react/react.js ENOSPC
    at exports._errnoException (util.js:1012:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (~/work/vue/browserify-hmr/example/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (~/work/vue/browserify-hmr/example/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (~/work/vue/browserify-hmr/example/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (~/work/vue/browserify-hmr/example/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (~/work/vue/browserify-hmr/example/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Fri, 19 Aug 2016 13:13:11 GMT] "GET /" "Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
[Fri, 19 Aug 2016 13:13:12 GMT] "GET /bundle.js" "Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
[Fri, 19 Aug 2016 13:13:12 GMT] "GET /bundle.js" Error (404): "Not found"
```
The version I used:
```
node: v6.3.1
npm:  v3.10.3
```

**Comment by AgentME** [comment]
I think npm failed at installing React correctly for you. Remove the node_modules directory inside the example directory, run `npm install` again, and see if it works after that.

**Comment by OwenChia** [comment]
Thanks.
I have tried remove `node_modules`  directory and reinstall it, still doesn't work.
But after I reboot my computer, it worked.  I dunno why, but it worked now.
